In [26]:
import nltk
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LinearRegression
from nltk.corpus import stopwords

In [27]:
# 
reviews = [
    "This book is amazing!",
    "The movie ending was so sad and left me with many emotions.",
    "I love the new product, it's fantastic!",
    "The game graphics are stunning, and the gameplay is addictive.",
    "The restaurant provided excellent service and delicious food.",
    "The quality of the service at this hotel is top-notch.",
    "I was disappointed with the plot twist in the film.",
    "The customer support for the product was terrible.",
    "The book is a masterpiece, highly recommend!",
    "The product didn't live up to my expectations, very dissatisfied.",
    "The game is a waste of time, don't bother playing it.",
    "The food at the restaurant was bland and tasteless.",
    "I'm thrilled with the outcome of the movie, it exceeded my expectations.",
    "The customer service was unresponsive and not helpful at all.",
    "This novel is a must-read, it captivates from the first page.",
    "The product is a great value for money, very pleased with my purchase.",
    "The game has too many bugs and glitches, it's unplayable.",
    "The hotel room was clean and comfortable, I had a pleasant stay.",
    "I regret buying the product, it's not worth the money.",
    "The film was boring, and I couldn't wait for it to end."
]

# 
for idx, review in enumerate(reviews):
    print(f"Review {idx + 1}: {review}")


Review 1: This book is amazing!
Review 2: The movie ending was so sad and left me with many emotions.
Review 3: I love the new product, it's fantastic!
Review 4: The game graphics are stunning, and the gameplay is addictive.
Review 5: The restaurant provided excellent service and delicious food.
Review 6: The quality of the service at this hotel is top-notch.
Review 7: I was disappointed with the plot twist in the film.
Review 8: The customer support for the product was terrible.
Review 9: The book is a masterpiece, highly recommend!
Review 10: The product didn't live up to my expectations, very dissatisfied.
Review 11: The game is a waste of time, don't bother playing it.
Review 12: The food at the restaurant was bland and tasteless.
Review 13: I'm thrilled with the outcome of the movie, it exceeded my expectations.
Review 14: The customer service was unresponsive and not helpful at all.
Review 15: This novel is a must-read, it captivates from the first page.
Review 16: The product is

In [28]:
# Загрузите стоп-слова для английского языка
nltk.download('stopwords')

# Создайте словарь стоп-слов для английского языка
stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [29]:
import re

cleaned_reviews = []
for review in reviews:
    cleaned_review = re.sub(r'[^\w\s]', '', review)  # Удаление символов пунктуации
    cleaned_reviews.append(cleaned_review)

print("Отзывы после очистки:")
for idx, cleaned_review in enumerate(cleaned_reviews):
    print(f"Отзыв {idx + 1}: {cleaned_review}")

Отзывы после очистки:
Отзыв 1: This book is amazing
Отзыв 2: The movie ending was so sad and left me with many emotions
Отзыв 3: I love the new product its fantastic
Отзыв 4: The game graphics are stunning and the gameplay is addictive
Отзыв 5: The restaurant provided excellent service and delicious food
Отзыв 6: The quality of the service at this hotel is topnotch
Отзыв 7: I was disappointed with the plot twist in the film
Отзыв 8: The customer support for the product was terrible
Отзыв 9: The book is a masterpiece highly recommend
Отзыв 10: The product didnt live up to my expectations very dissatisfied
Отзыв 11: The game is a waste of time dont bother playing it
Отзыв 12: The food at the restaurant was bland and tasteless
Отзыв 13: Im thrilled with the outcome of the movie it exceeded my expectations
Отзыв 14: The customer service was unresponsive and not helpful at all
Отзыв 15: This novel is a mustread it captivates from the first page
Отзыв 16: The product is a great value for mon

In [30]:
nltk.download('punkt')
# Примените стоп-слова к вашим отзывам
filtered_reviews = []
for review in reviews:
    words = nltk.word_tokenize(review.lower())
    filtered_review = ' '.join([word for word in words if word.isalpha() and word not in stop_words])
    filtered_reviews.append(filtered_review)

# Вывод отфильтрованных отзывов
for idx, filtered_review in enumerate(filtered_reviews):
    print(f"Отзыв {idx + 1} (отфильтрованный): {filtered_review}")

Отзыв 1 (отфильтрованный): book amazing
Отзыв 2 (отфильтрованный): movie ending sad left many emotions
Отзыв 3 (отфильтрованный): love new product fantastic
Отзыв 4 (отфильтрованный): game graphics stunning gameplay addictive
Отзыв 5 (отфильтрованный): restaurant provided excellent service delicious food
Отзыв 6 (отфильтрованный): quality service hotel
Отзыв 7 (отфильтрованный): disappointed plot twist film
Отзыв 8 (отфильтрованный): customer support product terrible
Отзыв 9 (отфильтрованный): book masterpiece highly recommend
Отзыв 10 (отфильтрованный): product live expectations dissatisfied
Отзыв 11 (отфильтрованный): game waste time bother playing
Отзыв 12 (отфильтрованный): food restaurant bland tasteless
Отзыв 13 (отфильтрованный): thrilled outcome movie exceeded expectations
Отзыв 14 (отфильтрованный): customer service unresponsive helpful
Отзыв 15 (отфильтрованный): novel captivates first page
Отзыв 16 (отфильтрованный): product great value money pleased purchase
Отзыв 17 (отфил

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [31]:
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.tokenize import word_tokenize
import nltk

nltk.download('punkt')
nltk.download('wordnet')

# Создаем объекты лемматизатора и стеммера
lemmatizer = WordNetLemmatizer()
stemmer = PorterStemmer()

lemmatized_reviews = []
stemmed_reviews = []

for review in cleaned_reviews:
    words = word_tokenize(review)
    
    lemmatized_review = ' '.join([lemmatizer.lemmatize(word) for word in words])
    stemmed_review = ' '.join([stemmer.stem(word) for word in words])
    
    lemmatized_reviews.append(lemmatized_review)
    stemmed_reviews.append(stemmed_review)

print("Отзывы после лемматизации:")
for idx, lemmatized_review in enumerate(lemmatized_reviews):
    print(f"Отзыв {idx + 1}: {lemmatized_review}")

print("\nОтзывы после стемминга:")
for idx, stemmed_review in enumerate(stemmed_reviews):
    print(f"Отзыв {idx + 1}: {stemmed_review}")


Отзывы после лемматизации:
Отзыв 1: This book is amazing
Отзыв 2: The movie ending wa so sad and left me with many emotion
Отзыв 3: I love the new product it fantastic
Отзыв 4: The game graphic are stunning and the gameplay is addictive
Отзыв 5: The restaurant provided excellent service and delicious food
Отзыв 6: The quality of the service at this hotel is topnotch
Отзыв 7: I wa disappointed with the plot twist in the film
Отзыв 8: The customer support for the product wa terrible
Отзыв 9: The book is a masterpiece highly recommend
Отзыв 10: The product didnt live up to my expectation very dissatisfied
Отзыв 11: The game is a waste of time dont bother playing it
Отзыв 12: The food at the restaurant wa bland and tasteless
Отзыв 13: Im thrilled with the outcome of the movie it exceeded my expectation
Отзыв 14: The customer service wa unresponsive and not helpful at all
Отзыв 15: This novel is a mustread it captivates from the first page
Отзыв 16: The product is a great value for money ve

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(filtered_reviews)

print("Матрица TF-IDF после удаления редких и частых слов:")
print(tfidf_matrix.toarray())
print("Слова в порядке их появления в матрице:")
print(tfidf_vectorizer.get_feature_names_out())


Матрица TF-IDF после удаления редких и частых слов:
[[0.         0.75108019 0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.48653258]
 [0.         0.         0.         ... 0.45774055 0.         0.        ]]
Слова в порядке их появления в матрице:
['addictive' 'amazing' 'bland' 'book' 'boring' 'bother' 'bugs' 'buying'
 'captivates' 'clean' 'comfortable' 'could' 'customer' 'delicious'
 'disappointed' 'dissatisfied' 'emotions' 'end' 'ending' 'exceeded'
 'excellent' 'expectations' 'fantastic' 'film' 'first' 'food' 'game'
 'gameplay' 'glitches' 'graphics' 'great' 'helpful' 'highly' 'hotel'
 'left' 'live' 'love' 'many' 'masterpiece' 'money' 'movie' 'new' 'novel'
 'outcome' 'page' 'playing' 'pleasant' 'please

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Создайте объект TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()

# Преобразуйте отфильтрованные отзывы в матрицу TF-IDF
tfidf_matrix = tfidf_vectorizer.fit_transform(filtered_reviews)

# Выведите матрицу TF-IDF
print("Матрица TF-IDF:")
print(tfidf_matrix.toarray())


Матрица TF-IDF:
[[0.         0.75108019 0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.48653258]
 [0.         0.         0.         ... 0.45774055 0.         0.        ]]


In [34]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
word_frequency_matrix = vectorizer.fit_transform(cleaned_reviews)

print("Матрица частот слов:")
print(word_frequency_matrix.toarray())
print("Слова в порядке их появления в матрице:")
print(vectorizer.get_feature_names_out())



Матрица частот слов:
[[0 0 1 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]]
Слова в порядке их появления в матрице:
['addictive' 'all' 'amazing' 'and' 'are' 'at' 'bland' 'book' 'boring'
 'bother' 'bugs' 'buying' 'captivates' 'clean' 'comfortable' 'couldnt'
 'customer' 'delicious' 'didnt' 'disappointed' 'dissatisfied' 'dont'
 'emotions' 'end' 'ending' 'exceeded' 'excellent' 'expectations'
 'fantastic' 'film' 'first' 'food' 'for' 'from' 'game' 'gameplay'
 'glitches' 'graphics' 'great' 'had' 'has' 'helpful' 'highly' 'hotel' 'im'
 'in' 'is' 'it' 'its' 'left' 'live' 'love' 'many' 'masterpiece' 'me'
 'money' 'movie' 'mustread' 'my' 'new' 'not' 'novel' 'of' 'outcome' 'page'
 'playing' 'pleasant' 'pleased' 'plot' 'product' 'provided' 'purchase'
 'quality' 'recommend' 'regret' 'restaurant' 'room' 'sad' 'service' 'so'
 'stay' 'stunning' 'support' 'tasteless' 'terrible' 'the' 'this'
 'thrilled' 'time' 'to' 'too' 'topnotch' 'twist' '

In [35]:
# from sklearn.linear_model import LinearRegression
# 
# # Создайте объект линейной регрессии
# model = LinearRegression()
# 
# # Обучите модель на матрице TF-IDF и фиктивных метках
# dummy_labels = [1] * len(filtered_reviews)  # Замените это реальными метками
# model.fit(tfidf_matrix, dummy_labels)
# 
# # Выведите коэффициенты модели
# coefficients = model.coef_
# intercept = model.intercept_
# 
# # Выведите коэффициенты
# print("Коэффициенты модели:", coefficients)
# print("Свободный член (intercept):", intercept)


In [36]:
for idx, review in enumerate(reviews):
    print(f"Review {idx + 1}: {review}")

Review 1: This book is amazing!
Review 2: The movie ending was so sad and left me with many emotions.
Review 3: I love the new product, it's fantastic!
Review 4: The game graphics are stunning, and the gameplay is addictive.
Review 5: The restaurant provided excellent service and delicious food.
Review 6: The quality of the service at this hotel is top-notch.
Review 7: I was disappointed with the plot twist in the film.
Review 8: The customer support for the product was terrible.
Review 9: The book is a masterpiece, highly recommend!
Review 10: The product didn't live up to my expectations, very dissatisfied.
Review 11: The game is a waste of time, don't bother playing it.
Review 12: The food at the restaurant was bland and tasteless.
Review 13: I'm thrilled with the outcome of the movie, it exceeded my expectations.
Review 14: The customer service was unresponsive and not helpful at all.
Review 15: This novel is a must-read, it captivates from the first page.
Review 16: The product is

In [37]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [38]:


# Задаем метки (0 - негатив, 1 - позитив)
labels = [1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0]

# Создаем DataFrame
df = pd.DataFrame({'review': reviews, 'label': labels})

# Преобразование текста отзывов в числовые признаки с помощью TF-IDF
tfidf_vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf_vectorizer.fit_transform(df['review'])

# Разделение данных на обучающий и тестовый наборы
X_train, X_test, Y_train, Y_test = train_test_split(tfidf_matrix, df['label'], test_size=0.2, random_state=42)

# Создание и обучение модели логистической регрессии
lr = LogisticRegression(solver='saga', max_iter=1000)
lr.fit(X_train, Y_train)

# Предсказание на тестовом наборе данных
y_pred = lr.predict(X_test)

# Оценка результатов
report = classification_report(Y_test, y_pred, output_dict=True)
print(report)

{'0': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 2.0}, '1': {'precision': 0.5, 'recall': 1.0, 'f1-score': 0.6666666666666666, 'support': 2.0}, 'accuracy': 0.5, 'macro avg': {'precision': 0.25, 'recall': 0.5, 'f1-score': 0.3333333333333333, 'support': 4.0}, 'weighted avg': {'precision': 0.25, 'recall': 0.5, 'f1-score': 0.3333333333333333, 'support': 4.0}}


C:\Users\user\PycharmProjects\pythonProject\venv\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\PycharmProjects\pythonProject\venv\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\PycharmProjects\pythonProject\venv\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_sta